---
title: "Cap4-Resumido"
author: "Carlos Souza"
date: "18/03/2021"
output: pdf_document
---

Capítulo 4

  Manipulando os dados

  Após obter uma boa fonte de dados, e carregá-los para poder trabalhá-los no R, você certamente precisará realizar algumas limpezas e manipulações para que os dados estejam no ponto ideal para as fases finais de uma análise: execução de modelos econométricos, visualizações de dados, tabelas agregadas, relatórios
etc. 
  A realidade é que, na prática, os dados nunca estarão do jeito que você de fato precisa. Portanto, é fundamental dominar técnicas de manipulação de dados.
Entendamos a manipulação de dados como o ato de transformar, reestruturar, limpar, agregar e juntar os dados. 
  Para se ter uma noção da importância dessa fase, alguns estudiosos da área de Ciência de Dados costumam afirmar que 80% do trabalho é encontrar uma boa fonte de dados, limpar e preparar os dados, sendo que os 20% restantes seriam o trabalho de aplicar modelos e realizar alguma análise propriamente dita. 
  
  "80% of data analysis is spent on the process of cleaning and preparing the data (Dasu and Johnson, 2003). 
  Data preparation is not just a first step, but must be repeated many over the course of analysis as new problems come to light or new data is collected (Hadley Wickham)."

4.1 Tipos de Variáveis e Colunas
  Existem diversos tipos de objetos, e cada tipo “armazena” um conteúdo diferente, desde tabelas de dados recém-carregados a textos, números, ou simplesmente a afirmação de verdadeiro ou falso (Boleano).
  
|  inteiro <- 928 outro.inteiro <- 5e2 |
|  decimal <- 182.93                   |
|  caracter <- 'exportação'            |
|  logico <- TRUE                      |
|  outro.logico <- FALSE               |
  
  Repare nas atribuições acima. Usaremos a função class() para ver o tipo de cada uma:
  
| class(inteiro)        |
| ## [1] "numeric"      |
| class(outro.inteiro)  |
| ## [1] "numeric"      |
|  class(decimal)       |
|  ## [1] "numeric"     |
|  class(caracter)      |
|  ## [1] "character"   |
|  class(logico)        |
|  ## [1] "logical"     |
|  class(outro.logico)  |
|  ## [1] "logical"     |

  Esses são alguns dos tipos básicos de objetos/variáveis no R. Para valores inteiros ou decimais, numeric, character para valores textuais e logical para valores lógicos (verdadeiro ou falso). Existe também o tipo integer, que representa apenas números inteiros, sem decimais, porém, na maioria das vezes, o R interpreta o integer como numeric, pois o integer também é um numeric.
  Além dos tipos básicos, existem também os tipos “complexos”, que são vector, array, matrix, list, data.frame e factor.
  Data frame é, provavelmente, o tipo de dado complexo mais utilizado em R. É nele que você armazena conjuntos de dados estruturados em linhas e colunas. Um data frame possui colunas nomeadas, sendo que todas as colunas possuem a mesma quantidade de linhas. Imagine o dataframe como uma tabela.
  
| class(senado)                       |
| ## [1] "tbl_df" "tbl" "data.frame"  |
| dim(senado)                         |
| ## [1] 9262 15                      |

  Outro tipo que já utilizamos bastante até agora, mas que não foi detalhado, é o vector, ou vetor. Vetores são sequências unidimensionais de valores de um mesmo tipo:
  
| #faça as seguintes atribuições :
|
| vetor.chr <- c('tipo1', 'tipo2', 'tipo3', 'tipo4')
| vetor.num <- c(1, 2, 5, 8, 1001)
| vetor.num.repetidos <- c(rep(2, 50)) #usando funcão para repetir números
| vetor.num.sequencia <- c(seq(from=0, to=100, by=5)) #usando função para criar 
| sequências
| vetor.logical <- c(TRUE, TRUE, TRUE, FALSE, FALSE)
|
| ##veja o conteúdo das variáveis
|
| vetor.chr
| ## [1] "tipo1" "tipo2" "tipo3" "tipo4"
|
| vetor.num
| ## [1] 1 2 5 8 1001
|
| vetor.num.repetidos
| ## [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
| ## [36] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
|
| vetor.num.sequencia
| ## [1] 0 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80
| ## [18] 85 90 95 100
|
| vetor.logical
| ## [1] TRUE TRUE TRUE FALSE FALSE

4.1.1 Conversões de tipos de variáveis
  Quando é feito o carregamento de algum arquivo de dados no R, ele tenta “deduzir” os tipos de dados de cada coluna. Nem sempre essa dedução sai correta e, eventualmente, você precisará converter de um tipo para o outro. O R tem algumas funções para fazer essas conversões.
  
| class("2015")       |
| ## [1] "character"  |
| as.numeric("2015")  |
| ## [1] 2015         |
| class(55)           |
| ## [1] "numeric"    |
| as.character(55)    |
| ## [1] "55"         |

4.1.3 Valores faltantes e o ‘NA’
  Em casos onde não existe valor em uma coluna de uma linha, o R atribui NA. É muito comum lidar com conjuntos de dados que tenham ocorrências de NA em alguns campos. É importante saber o que se fazer em casos de NA, e nem sempre a solução será a mesma: varia de acordo com as suas necessidades.
  Em algumas bases de dados, quem gera o dado atribui valores genéricos como 999 ou até mesmo um “texto vazio”, ' '. Neste caso, você provavelmente terá que substituir esses valores “omissos” por NA. 
  Imputar dados em casos de NA é uma das várias estratégias para lidar-se com ocorrência de missing no conjunto dos
dados.
  Seguem algumas funções úteis para lidar-se com NA:
  
• A função summary() pode ser usada para averiguar a ocorrência de NA.
• A função is.na() realiza um teste para saber se a variável/coluna possui um valor NA. retorna TRUE se for NA e FALSE se não for.
