---
title: "Cap6-Parte2-Resumido"
author: "Carlos Souza"
date: "23/03/2021"
output: pdf_document
---

6.2.3 Right Outer Join
  O princípio é EXATAMENTE o mesmo do left join. A única diferença é a permanência dos registros do conjunto é direita. Podemos chegar ao mesmo resultado anterior apenas mudando os data frames de posição na manipulação.

| > final3 <- departamentos %>% right_join(empregados, by = 
| c('Manager'='Employee'))
| > final3
| > ## # A tibble: 6 x 6
| > ## Department.x DepartmentName Manager EmployeeName Department.y Salary
| > ## <int> <chr> <int> <chr> <int> <int>
| > ## 1 11 Production 1 Alice 11 800
| > ## 2 NA <NA> 2 Bob 11 600
| > ## 3 NA <NA> 3 Carla 12 900
| > ## 4 12 Sales 4 Daniel 12 1000
| > ## 5 13 Marketing 5 Evelyn 13 800
| > ## 6 NA <NA> 6 Ferdinand 21 700
|
| > final2
| > ## # A tibble: 6 x 6
| > ## Employee EmployeeName Department.x Salary Department.y DepartmentName
| > ## <int> <chr> <int> <int> <int> <chr>
| > ## 1 1 Alice 11 800 11 Production
| > ## 2 2 Bob 11 600 NA <NA>
| > ## 3 3 Carla 12 900 NA <NA>
| > ## 4 4 Daniel 12 1000 12 Sales
| > ## 5 5 Evelyn 13 800 13 Marketing
| > ## 6 6 Ferdinand 21 700 NA <NA>

  A escolha entre right join e left join depende completamente da ordem em que você escolher realizar as operações. Via de regra, um pode ser substituído pelo outro, desde que a posi??o dos data frames se ajuste na sequência das manipulações.

6.2.4 Full Outer Join
  Existem, ainda, as situações em que é necessário preservar todos os registros de ambos os conjuntos de dados. O 'full join' tem essa característica. Nenhum dos conjuntos de dados perderá registros no resultado final, isto é?, quando as chaves forem iguais, todos os campos estarão preenchidos. Quando não houver ocorrência das chaves em ambos os lados, será informado NA em qualquer um deles.
  
| > band_members %>% full_join(band_instruments2, by = c('name' = 'artist'))
| > ## # A tibble: 4 x 3
| > ## name band plays
| > ## <chr> <chr> <chr>
| > ## 1 Mick Stones <NA>
| > ## 2 John Beatles guitar
| > ## 3 Paul Beatles bass
| > ## 4 Keith <NA> guitar

  Reparem que, dessa vez, não perdemos nenhum registro, de nenhum conjunto de dados, apenas teremos NA quando a ocorrência da chave não acontecer em alguns dos conjuntos.
  O full join funciona da seguinte forma:
  
| > final4 <- departamentos %>%
| > full_join(empregados, by = c('Manager'='Employee'))
| > final4
| > ## # A tibble: 7 x 6
| > ## Department.x DepartmentName Manager EmployeeName Department.y Salary
| > ## <int> <chr> <int> <chr> <int> <int>
| > ## 1 11 Production 1 Alice 11 800
| > ## 2 12 Sales 4 Daniel 12 1000
| > ## 3 13 Marketing 5 Evelyn 13 800
| > ## 4 14 Research NA <NA> NA NA
| > ## 5 NA <NA> 2 Bob 11 600
| > ## 6 NA <NA> 3 Carla 12 900
| > ## 7 NA <NA> 6 Ferdinand 21 700

  Do resultado desse full join, por exemplo, podemos concluir que n?o tem nenhum Manager no departamento Resarch, da mesma forma, os empregados Bob, Carla e Ferdinand não são managers de departamento nenhum.